import type { Metadata } from "next";
import { Modern_Antiqua } from "next/font/google";
import "./globals.css";

const modernAntique = Modern_Antiqua({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Social Media App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-secondary text-secondary-foreground dark:bg-primary dark:text-primary-foreground  ${modernAntique.className}`}
      >
        {children}
      </body>
    </html>
  );
}
